version: "3"

services:
  redis:
    image: redis:alpine
 
  api-gateway:
    build: ./api-gateway    
    ports:
      - 7000:7000
    environment:
      - BOOKING_URL=http://booking-service:3000
      - FEE_CALC_URL=http://fee-calculation-service:4000
      - PAYMENT_URL=http://payment-service:5000

  fee-calculation-service:
    build: ./fee-calculation-service
    environment:
      - REDIS_URL=redis://redis:6379/0
  booking-service:
    build: ./booking-service
  payment-service:
    build: ./payment-service
